version: "3"
services:
  test-db-tech:
    image: postgres:15.3
    restart: always
    ports:
      - "5433:5432" # 👈 Note the 5433 port for 2e2 tests
    environment:
      POSTGRES_PASSWORD: pass123
